### ISSUE TITLE
can not find some files

### ISSUE THREAD

**Issue by buer0** [SkywalkingContrib/skywalking-php-sdk#13]
in configure, try to rename such files:
grpc/greeter_client.cc \                            
      grpc/DiscoveryService.pb.cc \                                            
      grpc/DiscoveryService-grpc.pb.cc \                                
      grpc/ApplicationRegisterService.pb.cc \                           
      grpc/ApplicationRegisterService-grpc.pb.cc \                      
      grpc/TraceSegmentService.pb.cc \                                      
      grpc/TraceSegmentService-grpc.pb.cc
,but in dir grpc, there is no such files.

**Comment by songzhian** [comment]
Need to change  in config.m4  
KYWALKING_LIBS  and AC_OUTPUT_COMMANDS 
Associated GRPC

**Comment by heyanlong** [comment]
fixed
