### ISSUE TITLE
编译报错问题

### ISSUE THREAD

**Issue by nameless1987** [SkywalkingContrib/skywalking-php-sdk#27]
hecking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /opt/rh/devtoolset-4/root/usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /tmp/php
checking for PHP includes... -I/tmp/php/include/php -I/tmp/php/include/php/main -I/tmp/php/include/php/TSRM -I/tmp/php/include/php/Zend -I/tmp/php/include/php/ext -I/tmp/php/include/php/ext/date/lib
checking for PHP extension directory... /tmp/php/lib/php/extensions/no-debug-zts-20151012
checking for PHP installed headers prefix... /tmp/php/include/php
checking if debug is enabled... no
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking whether to enable skywalking support... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by cc... /opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld
checking if the linker (/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld) is GNU ld... yes
checking for /opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld option to reload object files... -r
checking for BSD-compatible nm... /opt/rh/devtoolset-4/root/usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 1572864
checking command to parse /opt/rh/devtoolset-4/root/usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld -m elf_x86_64
checking if the linker (/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
config.status: executing default-1 commands
./src/protos/*.proto: No such file or directory
./src/protos/*.proto: No such file or directory
config.status: executing default-2 commands
mv: cannot stat 'src/grpc/ApplicationRegisterService.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/Common.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/DiscoveryService.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/Downstream.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/JVMMetricsService.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/KeyWithIntegerValue.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/KeyWithStringValue.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/NetworkAddressRegisterService.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/TraceSegmentService.grpc.pb.cc': No such file or directory

**Comment by heyanlong** [comment]
retry 
`git clone --recurse-submodules https://github.com/SkywalkingContrib/skywalking-php-sdk.git`

**Comment by maopaolinux** [comment]
我也遇到了这个问题，请问如何处理？

**Comment by heyanlong** [comment]
@maopaolinux 问题发出来

**Comment by forthend** [comment]
编译报错：
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20170718
checking for PHP installed headers prefix... /usr/include/php/20170718
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable skywalking support... yes, shared
checking for libgrpc support... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for libgrpc files in default path... found in /usr/local
checking for grpc_channel_destroy in -lgrpc... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
config.status: executing default-1 commands
./src/grpc/: No such file or directory
./src/grpc/: No such file or directory
./src/grpc/: No such file or directory
./src/grpc/: No such file or directory
./src/grpc/: No such file or directory
./src/grpc/: No such file or directory
config.status: executing default-2 commands
mv: cannot stat 'src/grpc/common/common.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/register/Register.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/language-agent-v2/trace.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/register/InstancePing.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/common/trace-common.grpc.pb.cc': No such file or directory
config.status: executing libtool commands

**Comment by zsmlinux** [comment]
> 编译报错：
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking target system type... x86_64-pc-linux-gnu
> checking for PHP prefix... /usr
> checking for PHP includes... -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib
> checking for PHP extension directory... /usr/lib/php/20170718
> checking for PHP installed headers prefix... /usr/include/php/20170718
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... no
> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
> checking for gawk... gawk
> checking whether to enable skywalking support... yes, shared
> checking for libgrpc support... yes, shared
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking how to run the C++ preprocessor... g++ -E
> checking for libgrpc files in default path... found in /usr/local
> checking for grpc_channel_destroy in -lgrpc... yes
> checking how to print strings... printf
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking for fgrep... /bin/grep -F
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @file support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking for gawk... (cached) gawk
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for sysroot... no
> checking for a working dd... /bin/dd
> checking how to truncate binary pipes... /bin/dd bs=4096 count=1
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC -DPIC
> checking if cc PIC flag -fPIC -DPIC works... yes
> checking if cc static flag -static works... yes
> checking if cc supports -c -o file.o... yes
> checking if cc supports -c -o file.o... (cached) yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> checking how to run the C++ preprocessor... g++ -E
> checking for ld used by g++... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ option to produce PIC... -fPIC -DPIC
> checking if g++ PIC flag -fPIC -DPIC works... yes
> checking if g++ static flag -static works... yes
> checking if g++ supports -c -o file.o... yes
> checking if g++ supports -c -o file.o... (cached) yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> configure: creating ./config.status
> config.status: creating config.h
> config.status: executing default-1 commands
> ./src/grpc/: No such file or directory
> ./src/grpc/: No such file or directory
> ./src/grpc/: No such file or directory
> ./src/grpc/: No such file or directory
> ./src/grpc/: No such file or directory
> ./src/grpc/: No such file or directory
> config.status: executing default-2 commands
> mv: cannot stat 'src/grpc/common/common.grpc.pb.cc': No such file or directory
> mv: cannot stat 'src/grpc/register/Register.grpc.pb.cc': No such file or directory
> mv: cannot stat 'src/grpc/language-agent-v2/trace.grpc.pb.cc': No such file or directory
> mv: cannot stat 'src/grpc/register/InstancePing.grpc.pb.cc': No such file or directory
> mv: cannot stat 'src/grpc/common/trace-common.grpc.pb.cc': No such file or directory
> config.status: executing libtool commands

make之后出现以下报错：
make
/bin/sh /data/src/skywalking-php-sdk/libtool --mode=compile cc -Wall -Werror -std=c++11 -I. -I/data/src/skywalking-php-sdk -DPHP_ATOM_INC -I/data/src/skywalking-php-sdk/include -I/data/src/skywalking-php-sdk/main -I/data/src/skywalking-php-sdk -I/opt/php/php7.0.13/include/php -I/opt/php/php7.0.13/include/php/main -I/opt/php/php7.0.13/include/php/TSRM -I/opt/php/php7.0.13/include/php/Zend -I/opt/php/php7.0.13/include/php/ext -I/opt/php/php7.0.13/include/php/ext/date/lib -I/usr/local/include -I/data/src/skywalking-php-sdk/src/report/deps/boost -I/data/src/skywalking-php-sdk/src/grpc -I/data/src/skywalking-php-sdk/src  -DHAVE_CONFIG_H  -g -O2   -c /data/src/skywalking-php-sdk/skywalking.c -o skywalking.lo 
mkdir .libs
 cc -Wall -Werror -std=c++11 -I. -I/data/src/skywalking-php-sdk -DPHP_ATOM_INC -I/data/src/skywalking-php-sdk/include -I/data/src/skywalking-php-sdk/main -I/data/src/skywalking-php-sdk -I/opt/php/php7.0.13/include/php -I/opt/php/php7.0.13/include/php/main -I/opt/php/php7.0.13/include/php/TSRM -I/opt/php/php7.0.13/include/php/Zend -I/opt/php/php7.0.13/include/php/ext -I/opt/php/php7.0.13/include/php/ext/date/lib -I/usr/local/include -I/data/src/skywalking-php-sdk/src/report/deps/boost -I/data/src/skywalking-php-sdk/src/grpc -I/data/src/skywalking-php-sdk/src -DHAVE_CONFIG_H -g -O2 -c /data/src/skywalking-php-sdk/skywalking.c  -fPIC -DPIC -o .libs/skywalking.o
cc1: error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
make: *** [skywalking.lo] Error 1
